### ISSUE TITLE
Mix.exs license doesn't match LICENSE file

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [arianvp/elixir-isaac#1]
The license specified in `Mix.exs` is GPLv3, while the LICENSE file is for the unlicense. If you intended to dual license the project, then I believe `:licenses` supports multiple licenses, otherwise it's probably best to just pick one (presumably the unlicense, given its permissiveness)

**Comment by arianvp** [comment]
Hey thanks for the heads up.  Unlicense was the one I want as  ISAAC is in the public domain https://en.wikipedia.org/wiki/ISAAC_(cipher)

**Comment by arianvp** [comment]
Fixed in https://github.com/arianvp/elixir-isaac/commit/abc7636612852cb074c02c46e7acf3cac3847953
